fancy-regex/fancy-regex

.travis.yml
AUTHORS
CONTRIBUTING.md
Cargo.toml
LICENSE
README.md
benches/bench.rs
examples/toy.rs
src/analyze.rs
src/compile.rs
src/lib.rs
src/parse.rs
src/vm.rs

We're moving the repo to the new "fancy-regex" organization. This
patch updates the copyright headers and other metadata.
The contribution guidelines have been updated (adopting the Rust
Code of Conduct), and the README freshened up just a bit.

Update metadata for repo move

---

.travis.yml

Apparently it needs that option now, see https://github.com/xd009642/tarpaulin#usage

travis: Fix cargo tarpaulin

---

.travis.yml

See https://github.com/xd009642/tarpaulin#travis-ci-and-coverage-sites
The previous PR fixed the installation, but then running it didn't produce any results.
This should fix that :).

travis: Change sudo to required for cargo-tarpaulin

---

.gitignore
src/lib.rs
tests/captures.rs

That was broken in 0.1.0, see https://github.com/google/fancy-regex/issues/49

Add test for captures

---

.travis.yml
Cargo.toml
src/lib.rs
src/vm.rs

1.24.1 is the minimal supported Rust version of the regex crate, see [CHANGELOG](https://github.com/rust-lang/regex/blob/master/CHANGELOG.md). It
probably makes sense to support the same.

Bump dependencies and test against Rust 1.24.1

---

src/lib.rs
tests/finding.rs

Match is the same as in the regex crate to make the APIs more similar.

Change find to return a Match struct and add more documentation

---

src/lib.rs
tests/oniguruma/test_utf8_ignore.c

Makes delegate regexes easier to read.

Simplify generated regex for repeats

---

src/vm.rs
tests/finding.rs
tests/oniguruma/test_utf8_ignore.c

Note that the tests still fail because `()*` doesn't capture in our implementation (neither does it in regex).
In Oniguruma, it captures the empty string, so `()*\1` matches.

Fix panic for matching backref to unmatched group

---

CHANGELOG.md
src/analyze.rs
src/compile.rs
tests/finding.rs

The logic was the wrong way around, so a case-insensitive literal was being
compiled as case-sensitive.
Also found by writing tests for uncovered branches.

Fix fancy casei literal compilation

---

src/vm.rs
tests/finding.rs

The test failed like this before:
thread 'backref_with_multibyte' panicked at
'byte index 10 is not a char boundary;
it is inside '🐱' (bytes 9..13) of `x🐱🐶🐱🐶`',
src/libcore/str/mod.rs:2068:5

Fix backref with multibyte chars

---

src/error.rs
src/lib.rs

That enabled users to propagate it in a generic way or use it as a source for
other errors.
Also, moved the error types to a module. We should do that for the other types in `lib.rs` as well to have a bit more structure.

Make Error implement std::error::Error trait

---

src/compile.rs
src/lib.rs

I want to have these options for parsing user-agent regexes in https://github.com/davidarmstronglewis/uap-rs, which parse fine with this crate and onig, but are just too large.

Add options for controlling program and dfa size limits

---

CHANGELOG.md
src/compile.rs
tests/matching.rs

Some regexes with fancy parts in the beginning/middle didn't match when
they should have, e.g. `((?!x)(a|ab))c` didn't match `abc` because
`(a|ab)` was delegated and so never backtracked to `ab`.
Fixes #37.

Fix over-eager delegation preventing matching

---

benches/bench.rs
src/compile.rs
src/lib.rs
src/vm.rs

For a fully delegated regex that means we don't need inner1 anymore
(only 1 regex instead of 2). With that we can also simplify the captures
implementation.

Use captures_read_at

---

CHANGELOG.md
src/parse.rs
tests/oniguruma/test_utf8_ignore.c

Same as Oniguruma. See https://github.com/trishume/syntect/issues/287 where the lack of support for this is a problem.

Support comments using `(?# comment)` syntax

---

CHANGELOG.md
src/parse.rs
tests/oniguruma/test_utf8_ignore.c

For https://github.com/trishume/syntect/issues/287

Support \u and \U unicode escapes

---

CHANGELOG.md
src/error.rs
src/parse.rs
tests/oniguruma/test_utf8_ignore.c

Makes it easier to identify the problem. Before:
```
"Unknown group flag"
"Invalid escape"
```
After:
```
"Unknown group flag: (?<"
"Invalid escape: \g"
```
(For https://github.com/trishume/syntect/issues/287)

Include string snippet in errors for unknown group and invalid escape

---

src/error.rs
src/parse.rs
tests/oniguruma/test_utf8_ignore.c

I implemented _basic_ named groups support based on your comments in issue #34 . Everything is done in parser.rs by keeping keep track of the group number being parsed and using a HashMap to map named group IDs to the numbers.
The result was being able to pass one more internal test and eight more onigurama tests. I'm a little confused as to how (why?) they support some things like non-unique group names. I'm also struggling to grasp the difference between "\g" and "\k" in this context.

Initial named group support

---

Cargo.toml

We should probably consider committing Cargo.lock to not get failures
like this when dependencies upgrade and break compatibility.

Try to fix build on Rust 1.32

---

src/expand.rs
src/lib.rs
tests/captures.rs

Adds a method similar to regex::Captures::expand, an alternate version using Python-style syntax, and a API for flexible expansion string syntax.
Not expected to build with PR #55.

Added expansion APIs

---

src/expand.rs
src/lib.rs
tests/captures.rs

This adds the error checking method I mentioned before, and it fixes a bug in `append_expansion` that causes the initial contents of `dst` to be overwritten.

Added error checking and fixed append_expansion.

---

src/lib.rs

- These are ported from `regex` crate.
- Added `Match::range()`
- Added description for `Match::new()`
- Implemented `From<Match>` for string slice and `Range<usize>`.

Added: `Match:range()` method

---

.github/workflows/ci.yml

See https://github.com/xd009642/tarpaulin/issues/461#issuecomment-753466606
Looks like the latest version (0.17.0) is broken. It has been yanked
from crates.io but the Docker image is still on that. Use a pinned
version, which is better for CI anyway.

CI: Fix coverage action

---

.github/workflows/ci.yml

It's not deterministic enough to run it on a schedule. Additionally, it
would be nice to be able to run the newest clippy but not have it
complain about things that can't be fixed without bumping the MSRV.

Remove clippy from CI

---

.github/workflows/ci.yml
Cargo.toml
src/vm.rs

The byteorder crate recently bumped to 1.41.1 and didn't compile on
1.32.0 anymore:
https://github.com/BurntSushi/byteorder/pull/171
So we'd either need to pin byteorder to an older version or bump our
MSRV. 1.41.1 is the version that's in Debian stable, that's new enough.
It also means we can add back clippy.

Bump MSRV to 1.41.1

---

README.md
src/lib.rs
tests/captures.rs
tests/finding.rs

Hi!
This PR would fix #59 by adding `find_iter` and `captures_iter`. I also had to add `find_from_pos` which is called repeatedly by `find_iter` now. The implementations are adapted from the regex crate with minimal modifications.
Some things worth noting:
- There is some code duplication between the `Iterator` impl for `Matches` and `CaptureMatches`. This is also the case in the regex crate and I didn't see an easy way to avoid this.
- I had to copy the `next_utf8` method from the regex crate to move forward in case of an empty match. I made a note in the doc string.
Before this is merged, the current status in the Readme should also be updated.
Please let me know what you think!

add find_iter, captures_iter (and find_from_pos)

---

tests/oniguruma.rs
tests/oniguruma/test_utf8_ignore.c

Checking that the failure starts with the expected failure string makes it possible to just match on the error code, not the full message.
The exact matching before [broke the build](https://github.com/fancy-regex/fancy-regex/runs/2514520304?check_suite_focus=true) because regex started escaping `'` in messages differently.

Make checking for specific failure message less strict

---

src/lib.rs
src/vm.rs
tests/captures.rs

Adds the following implementations on the `Regex` and `Captures` structs. These implementations follow those in the `regex` crate, and in some cases are direct copies.
* `impl fmt::Display for Regex`
* `impl<'t> Index<usize> for Captures<'t>` (index capture groups by `usize`)
* `impl<'t, 'i> Index<&'i str> for Captures<'t>` (index capture groups by name)
* `impl Clone for Regex` (also implements for `RegexImpl`, `vm::Insn`, `vm::Prog`, which `Regex` relies on)
Addresses #72 and at least part of #71 (not sure if it totally covers the need described there).

Implement some common traits on Regex & Captures

---

src/lib.rs
src/replacer.rs
tests/replace.rs

Closes #49
Most of this code is verbatim copy from the `regex` crate.
License: MIT OR Apache-2.0
Author: Andrew Gallant <jamslam@gmail.com>
Author: Alex Crichton <alex@alexcrichton.com>
Author: Lapinot <peio.borthelle@ens-lyon.fr>
Author: tom <nooberfsh@gmail.com>
Author: Matt Brubeck <mbrubeck@limpet.net>
Author: Marti Raudsepp <marti@juffo.org>
Methods:
* Regex::replace() -- single replacement
* Regex::replace_all() -- replace all non-overlapping matches
* Regex::replacen() -- configurable number of replacements
Traits:
* Replacer -- describes logic for replacing matches
Trait implementations included for `&str`, `String`, `NoExpand`, `FnMut(&Captures)->str`
Structs:
* NoExpand -- Replacer that performs no substitutions
* ReplacerRef -- by-reference adaptor

Add replace*() methods similar to regex crate

---

src/error.rs
src/parse.rs
tests/oniguruma/test_utf8_ignore.c

Fixes #68 and matches Oniguruma behavior

Disallow quantifers on lookarounds and other zero-width assertion expressions

---

fuzz/.gitignore
fuzz/Cargo.toml
fuzz/fuzz_targets/fuzz_parser.rs

I just deleted the fuzzer and regenerated it so that I can use `data: &str`

Update fuzzing harness, use correct name to parse expr

---

Cargo.toml

Allow users to disable any of the `unicode` and `perf-*` features of the `regex` crate.  Disabling these features can reduce compile time and/or binary size for use cases where these features are not needed.  (All features remain enabled by default.)

Enable selection of regex crate features

---

CHANGELOG.md
src/analyze.rs
src/compile.rs
src/lib.rs
src/parse.rs
src/vm.rs
tests/captures.rs
tests/finding.rs
tests/oniguruma/test_utf8_ignore.c

Fixes #87 
Note: I haven't looked into how oniguruma handles `\K` inside lookarounds yet.

Add support for \K keep out

---

CONTRIBUTING.md
src/lib.rs

and mention it in the contributing guide to help prevent it from being missed again in future

Update docs to include new syntax

---

AUTHORS
CHANGELOG.md
src/analyze.rs
src/compile.rs
src/lib.rs
src/parse.rs
src/vm.rs
tests/finding.rs
tests/oniguruma/test_utf8_ignore.c

Adds support for `\G` - anchor to where the previous match ended. https://www.regular-expressions.info/continue.html

Add support for \G - anchor to previous match end

---

benches/bench.rs
src/vm.rs
tests/matching.rs

This can happen when a backref is used within the group it references, see added test case.
Note that in the bench, a similar regex is used but because it's using a lower level API, the `\1` refers to the second set of parentheses (the first is the match itself).

Fix panic when group end index is not known yet (fixes #103)

---

.github/workflows/ci.yml

Error:
> Unable to locate build via Github Actions API. Please upload with the
> Codecov repository upload token to resolve issue.
See https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954

Use CODECOV_TOKEN to avoid sporadic errors

---

.github/workflows/ci.yml

Coverage step would [fail](https://github.com/fancy-regex/fancy-regex/actions/runs/5340844781/jobs/9681088791) after a while with "Too many uploads to this commit", so don't run coverage on schedule (not necessary anyway).

CI: Run schedule less frequently, don't run coverage

---

.github/workflows/ci.yml
Cargo.toml
src/analyze.rs
src/compile.rs
src/error.rs
src/expand.rs
src/lib.rs
src/parse.rs
src/replacer.rs
src/vm.rs

[The `regex` crate added `no_std` support in a recent release](https://github.com/rust-lang/regex/blob/master/CHANGELOG.md#190-2023-07-05). This PR adds `no_std` support to `fancy_regex`, which mostly consists of just changing some imports from `std::` to their `core::` and `alloc::` counterparts.
~~The largest change is switching from the standard `HashMap` to the one provided by `hashbrown`.~~

Add no-std support

---

src/error.rs

This brings it to parity with the underlying [regex](https://docs.rs/regex/latest/src/regex/error.rs.html#8-32) library

Make Error and its components Clone

---

src/error.rs

CC @ruihe774 pulled this change out.

Use `#[non_exhaustive]`

---

src/parse.rs

It wasn't checking for a closing paren but instead just incremented ix, leading to an index out of bounds later.
Fixes #122.

Fix index out of bounds caused by parse_conditional

---

src/parse.rs
tests/oniguruma/test_utf8_ignore.c

See:
* https://github.com/fancy-regex/fancy-regex/pull/121#issuecomment-1857255661

Undo parsing \g as backref

---

README.md

Replace broken link to paper on the authors homepage with a version hosted on arXiv. In the current version, the example in the README appears on page 2.

Fix broken link to "Static Analysis for Regular Expression" paper

---

src/lib.rs

Adds a `try_replacen` function that returns a `Result` and propagates any errors. `replacen` now wraps this.

Add `try_replacen`

---

src/lib.rs
tests/splitting.rs

Closes #104
This pull request introduces a Split struct and a corresponding split method to the Regex struct. This enhancement allows users to split a target string by the matches of a regex, yielding an iterator of substrings that are not matched by the regex.
(I referenced the code in #104 .)
- **Created `Split` Struct**: Implemented the `Iterator` trait for the `Split` struct, allowing it to return the next substring from the target string based on regex matches.
- **Added `split` Method**: Implemented the `split` method in the `Regex` struct to return an instance of the `Split` iterator.
- **Documentation**: Provided documentation for the `split` method, including usage examples.
- **Test Cases**: Added test cases in `tests/splitting.rs` to verify the functionality of the `split` …

Add Split Struct and split Method to Regex

---

src/lib.rs
tests/splitting.rs

This pull request introduces the `SplitN` functionality to the `Regex` struct, allowing users to split a target string by the matches of a regex with a limit on the number of splits (`N`). The last substring returned is the remainder of the target string.
- **Created `SplitN` Struct**: Implemented the `Iterator` trait for the `SplitN` struct, which contains a`Split` and a `limit` for the maximum remaining splits.
- **Added `splitn` Method**: Added the `splitn` method to the `Regex` struct to return an instance of the `SplitN` iterator.
- **Documentation**: Updated the documentation with examples on how to use the `splitn` method.
- **Test Cases**: Updated test cases in `tests/splitting.rs` to verify the functionality of the `splitn` method.
```rust
use fancy_regex::Regex;
let re = …
```

Add SplitN Struct and splitn Method to Regex

---

src/analyze.rs
src/compile.rs
src/error.rs
src/lib.rs
src/parse.rs
tests/oniguruma/test_utf8_ignore.c

I had the idea to implement subroutine calls, so this represents the first stage of the work - parsing the regex patterns.
Hopefully doing it in stages will make the PRs smaller and easier to review. Later will come the real changes to the analyzer, compiler and VM itself. This means I had to introduce a new `CompileError` to represent features which are recognized by the parser but are as yet unsupported for actually performing matches.
Partially inspired by:
- https://github.com/fancy-regex/fancy-regex/issues/141
- https://github.com/sharkdp/bat/issues/3156
Currently builds upon https://github.com/fancy-regex/fancy-regex/pull/148, as that improved test coverage etc.

Update parser to support parsing subroutine call syntax

---

.github/workflows/ci.yml
Cargo.toml
examples/toy.rs
src/compile.rs
src/lib.rs
src/vm.rs

The `toy` example had a number of shortcomings:
- the debug output was too verbose - it showed the PikeVM debug output instead of the regex pattern for example, making the graph unreadably big
- it panicked with regex patterns which include backrefs etc. due to the analyzed expression tree missing instructions for the 0th group
This PR fixes those problems and adds some tests which verify the output from the `toy` example, and runs those tests in CI.

Fix toy example

---

src/lib.rs
src/parse.rs
tests/oniguruma/test_utf8_ignore.c

this simple change gets a few more Oniguruma test cases passing, no need for any new Exprs or anything :)

support \O to match any character including a newline

---

src/parse.rs
tests/oniguruma/test_utf8_ignore.c

We previously supported the angle bracket `(?<name>...)` syntax but missed the single quoted variant which Oniguruma supports

Add support for named captures using (?'name'...) syntax

---

src/parse.rs

to match Oniguruma, we should emit a parse error when quantifiers are used on assertions and other Expr nodes where it makes no sense to have a quantifier

Mark more expressions as non-repeatable

---

src/analyze.rs
src/compile.rs
src/error.rs
src/lib.rs
src/parse.rs
tests/oniguruma/test_utf8_ignore.c

Oniguruma supports calls to subroutines which haven't been parsed yet. To cater for this, when we come across such a subroutine call, we initially emit an `Expr::UnresolvedNamedSubroutineCall`. Then, once parsing of the entire regex pattern has completed, if there were any unresolved named subroutine calls, it goes through and resolves them - replacing them with a numbered `Expr::SubroutineCall`. If there are still any such `UnresolvedNamedSubroutineCall` exprs left at analyze time, then we fail immediately. The compiler will never see this expr.

Support named subroutine calls defined later on in the expression

---

src/analyze.rs
src/compile.rs
src/expand.rs
src/lib.rs
src/parse.rs
tests/oniguruma/test_utf8_ignore.c

Basically a backref can either be to a relative group number like `(1)\k<-1>)` or it can be specifying a relative recursion level, but not both. When specifying a relative recursion level, the group number has to be absolute. So I updated `parse_id` to handle that, and callers then choose how to interpret the relative part based on the context.

Update parser to support backrefs with a relative recursion level

---

.github/workflows/ci.yml
benches/bench.rs
examples/toy.rs
src/analyze.rs
src/compile.rs
src/error.rs
src/expand.rs
src/lib.rs
tests/captures.rs
tests/oniguruma/test_utf8_ignore.c

as discussed in #167, this PR removes the need to wrap the `ExprTree` to get the match bounds or allow the match to start at any position. This opens up the optimization to perform an anchored search when the regex pattern begins with `^` meaning start of text (as opposed to start of line), by not emitting instructions to bump the index in the haystack. The end result being that it should fail faster for non-matches. (I'm leaving it as a future optimization to let regex-automata perform unanchored regex searches for the first `Delegate` etc.)
- instead of prepending `(?m:.*?)` to the `ExprTree`, add the instructions at compile time
Other changes:
- also ensure that benchmarks compile as part of CI
- the CompileError for an invalid (numbered) backref has been updated to mention which …

Refactor to avoid wrapping exprtree

---

.github/FUNDING.yml
.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
PERFORMANCE.md
README.md
benches/bench.rs
examples/toy.rs
src/analyze.rs
src/compile.rs
src/lib.rs
src/optimize.rs
src/parse.rs
tests/captures.rs
tests/matching.rs

Basically combines https://github.com/fancy-regex/fancy-regex/pull/167 and https://github.com/fancy-regex/fancy-regex/pull/170 (and adapts the trailing lookahead optimization now that the `ExprTree` isn't wrapped) - as I had made those PRs from my fork, it wasn't trivial to stack them...

Trailing positive lookahead optimization including wrap elimination

---

src/vm.rs
tests/finding.rs
tests/oniguruma/test_utf8_ignore.c

Previously it would fail the branch when a repetition resulted in an empty match, but Oniguruma treats it as success if enough iterations were completed and breaks out the repetition. So the change is to match Oniguruma behavior. Fixes #70 
I also noticed a test case which after the trailing lookahead optimizations, wasn't testing what it should, so I fixed it.

Fix behavior of repetition on an empty match

---

playground/web/app.js
playground/web/index.html
playground/web/utf8_string.js

Fix highlighting when multibyte characters are in the test text, and update the default example text to demonstrate that it works.
Plus a few other misc changes in the playground:
- show analysis and parse tree even for an empty pattern
- keep the parse tree and analysis in sync when there is a parse error. Previously it kept the previous output which could be confusing. Also the redundant/duplicated error prefixes have now been removed.

Fix highlighted text misalignment in playground when multi-byte chars are present
