fancy-regex/fancy-regex

.travis.yml

See https://github.com/rust-lang/cargo/issues/6015

travis: Run coverage on nightly instead of stable

---

benches/bench.rs
examples/toy.rs
src/analyze.rs
src/compile.rs
src/lib.rs
src/parse.rs
src/vm.rs
tests/captures.rs
tests/common/mod.rs
tests/finding.rs
tests/matching.rs

I think I'm happy with using the default configuration, no need to change anything.

Format using rustfmt 1.0.1-stable

---

CHANGELOG.md
examples/toy.rs
src/lib.rs
tests/captures.rs

Similar to #11, this makes the API closer to the regex crate's API.

Change Captures API to use Match as well

---

.travis.yml
src/lib.rs

It can be a bit annoying while developing.

Move deny warnings to Travis build

---

src/vm.rs

More readable than tuples especially where we do .0 or .2.

Use structs instead of tuples for State contents

---

src/vm.rs
tests/matching.rs

There was no test coverage before.

Add tests for backtrack_cut and comment code

---

src/lib.rs
tests/captures.rs
tests/finding.rs

Found a bug, see change in lib :).

Add more tests for uncovered branches

---

CHANGELOG.md
benches/bench.rs
examples/toy.rs
src/lib.rs
src/vm.rs
tests/matching.rs

Add limit for backtracking in case of catastrophic backtracking

---

src/compile.rs

The Vec was only needed because compile_concat had to pass in a
`&[&Info<'_>]`. By splitting the slice and single element cases, we can
just pass in the `&[Info<'_>]` that we have.

Refactor compile_delegates to avoid Vec

---

Cargo.toml
src/vm.rs

No more rand dependency necessary, yay.

Update to quickcheck 1.0

---

CHANGELOG.md
src/parse.rs
tests/finding.rs

fix: Panic on incomplete escape sequences in input regexes

---

.github/workflows/ci.yml
src/vm.rs

Also add a GitHub action for it.

Fix toy example with recent changes (no start/end match) (#90)

---

CHANGELOG.md
src/lib.rs
src/vm.rs

Extend docs/comments for \K and \G

---

.github/workflows/ci.yml

See https://github.com/actions-rs/toolchain/issues/216

CI: Replace actions-rs

---

CHANGELOG.md
CONTRIBUTING.md

@ruihe774 did I miss anything from the big PR?

Prepare CHANGELOG for next release

---

Cargo.toml

Mostly to eventually resolve the root of this:
https://github.com/emilk/egui/actions/runs/9998324899/job/27636936694?pr=4847

Update bit-set to 0.8

---

.github/workflows/ci.yml
src/lib.rs
src/parse.rs
tests/finding.rs
tests/oniguruma/test_utf8_ignore.c

Implement \Z

---

src/lib.rs
tests/captures.rs
tests/finding.rs

fix infinite loop when backtracking limit is hit

---

src/expand.rs
src/parse.rs

improvements from PR #157 review

Relative recursion parse improvements

---

CHANGELOG.md
src/analyze.rs
src/parse.rs

Fix to ensure it always picks up invalid backrefs

---

src/lib.rs

Always return the original input pattern when as_str is called
